name: Publish

on:
  workflow_dispatch:

jobs:
  maven-central:
    name: Maven Central
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Release
        shell: bash
        env:
          SONATYPE_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          PGP_SECRET: ${{ secrets.GPG_SIGNING_KEY }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        run: |
          : Release
          (
            umask 0077
            mkdir -p ~/.gnupg/private-keys-v1.d
          )
          
          export GPG_TTY=$(tty)
          echo "$PGP_SECRET" | base64 -d | gpg --batch --allow-secret-key-import --import
          sbt "clean; reload; compile; +publishSigned; sonatypeBundleRelease"
